# deadlock-japanese
Localizing Valve's game 'Deadlock' into Japanese

Valve社からパブリッシュされているゲーム `Deadlock` を日本語化する設定ファイルです。 +
この設定ファイルは有志のユーザーによって作られています。 +
全ての権利は `Valve Corporation©` に帰属します。

翻訳の修正・改善提案は随時受け付けています。ご協力お願い致します。 + 
`ここの翻訳が足りていない`, `ここの日本語訳をこうしてほしい`, `新しいbuildバージョンに対応して欲しい`, etc...

* https://forms.gle/AYovpxB2JmRsaGsGA[Google formで提案する^]
* https://github.com/NPJigaK/deadlock-japanese/issues[Githubで直接提案する（Githubアカウントをお持ちの方）]

## 対応バージョン
----
Build 5.115 2024/08/30 - 21:09:58
----
※基本的にbuildバージョンが違くても翻訳可能ですが、新しいbuildバージョンで設定値が増えていた場合、そこだけ英語のままになります。

ヒーロー名は英語のままにしています。 +
ショップのアイテム名は英語のままにしています。 +

## 設定方法

. https://github.com/NPJigaK/deadlock-japanese/archive/refs/heads/main.zip[こちら]から最新版の日本語化設定ファイルをダウンロードしてください
.. zipファイルでダウンロードされます。解凍後、 `game` フォルダが入っていることを確認してください。
. ゲームがインストールされているフォルダ（例: `C:\Program Files (x86)\Steam\steamapps\common\Deadlock`）を開く
.. インストールされているフォルダが分からない場合は、steamを開いて、ライブラリからdeadlockを右クリックしてプロパティを開き、インストール済みファイルタブにある参照ボタンを押すと直接開けます。
. `game` フォルダを、先ほどダウンロードしたフォルダの中にある `game` フォルダで上書きします
.. 上書き後に以下のような構成になっていれば大丈夫です。（ファイルを追加したフォルダのみ表示しています）
+
[source, 例: C:\Program Files (x86)\Steam\steamapps\common\Deadlock\]
----
game
└─ citadel
   └─ resource
      └─ localization
         ├─ citadel_attributes
         │  ├─ citadel_attributes_english.txt など...
         │  └─ citadel_attributes_japanese.txt <- 今回追加したファイル
         ├─ citadel_gc
         │  ├─ citadel_gc_english.txt など...
         │  ├─ citadel_gc_japanese.txt <- 今回追加したファイル
         │  └─ ex-citadel_gc_japanese.txt <- ショップのアイテムを日本語表示にしたい方向け                               
         ├─ citadel_heroes
         │  ├─ citadel_heroes_english.txt など...
         │  └─ citadel_heroes_japanese.txt <- 今回追加したファイル
         ├─ citadel_main
         │  ├─ citadel_main_english.txt など...
         │  └─ citadel_main_japanese.txt <- 今回追加したファイル
         └─ citadel_mods
            ├─ citadel_mods_english.txt など...
            └─ citadel_mods_japanese.txt <- 今回追加したファイル
----
. Steamを開いて、ライブラリからdeadlockを右クリックしてプロパティを開き、起動オプションに以下を入力してください。
+
[source, 起動オプション]
----
-language japanese
----
. Deadlockを起動して、日本語化されていればOKです

## 更新履歴

### 2024/09/01
*※ 大きな変更があります* +
https://x.com/steinsgg/status/1829208615779217490[Xで実施したアンケート]結果とフォームで頂いた提案に基づいて、以下の変更を加えました。

* *ショップのアイテム名を英語に戻しました。*
** アイテムは名前で並び順が変わってしまい、ビルドに影響が出てしまうためです。
** 以前までのアイテム名が日本語翻訳されたファイルは `ex-citadel_gc_japanese.txt` として残しています。 + 
アイテム名も日本語でプレイしたい方は、ファイル名を `citadel_gc_japanese.txt` にリネームしてからファイルの上書きをしてください。
* *ヒーローのアビリティ名をカタカナ読みに変更しました。*
** アビリティ名は名前で並び順が変わらないため、どなたでも読めるカタカナ読みにします。 + 
併せて英語のアビリティ名を説明欄に表示するようにしました。
* `スロー`（移動速度低下）の表記を `スロウ` に修正しました。

### 2024/08/31
* 最新版 `Build 5.115 2024/08/30 - 21:09:58` に対応しました。
* 一部アビリティ説明のパラメータが正しく引用されていない問題を修正しました。
* 起動オプションの誤記を修正しました。`en-dash (–)` で表記していましたが正しくは `hyphen (-)`
* ヒーロー `Viscous` の3番目のアビリティが正しく表示されていない問題を修正しました。
* ヒーロー `Warden` の3番目のアビリティをより分かりやすく再翻訳しました。
* `Health` の翻訳を `体力` に統一しました。

### 2024/08/30 
* 最新版 `Build 5.106 2024/08/29 - 23:02:44` に対応しました。
* ヒーロー `Mirage` のアビリティ `ファイアービートル` の説明文を修正しました。
* 公式で対応されたため `core` フォルダ配下の日本語化設定ファイルを削除しました。

### 2024/08/29 
* 最新版 `Build 5.095 2024/08/27 - 19:03:02` に対応しました。

### 2024/08/28 
* 日本語化設定ファイルを作成・公開
