:toc: left
:toc-title: 目次
:note-caption: 💡

# deadlock-japanese
Localizing Valve's game 'Deadlock' into Japanese

Valve社からパブリッシュされているゲーム `Deadlock` を日本語化する設定ファイルです。 +
この設定ファイルは有志のユーザーによって作られています。 +
全ての権利は `Valve Corporation©` に帰属します。

翻訳の修正・改善提案は随時受け付けています。ご協力お願い致します。 + 
例：`ここの日本語訳が足りていない`, `ここの日本語訳を分かりやすくしてほしい`, `新しいbuildバージョンに対応して欲しい`, etc...

* https://forms.gle/AYovpxB2JmRsaGsGA[Google formで提案する^]
* https://github.com/NPJigaK/deadlock-japanese/issues[Githubで直接提案する（Githubアカウントをお持ちの方）]

その他の質問に関してましては link:https://x.com/steinsgg/status/1831259780293538199[X(Twitter)] にて相談を受け付けております。お気軽にご相談ください。

## 対応バージョン
----
Build 5.123 2024/09/05 - 23:22:04
----

[NOTE]
======
基本的にbuildバージョンが違くても日本語化出来ます。新しいbuildバージョンでヒーローやアイテムが増えていた場合、そこだけ英語のままになりますので、定期的に最新の日本語化設定ファイルに更新することをお勧めします。
======

*ヒーロー名、ショップのアイテム名は英語のままにしています。* + 
ショップのアイテム名は日本語にすることも可能です。詳しくは<<section-items-to-japanese,こちら>>を参照ください。

[[section-settings]]
== 設定方法

. https://github.com/NPJigaK/deadlock-japanese/archive/refs/heads/main.zip[こちら]から最新版の日本語化設定ファイルをダウンロードしてください
.. zipファイルでダウンロードされます。解凍後、 `game` フォルダが入っていることを確認してください。
. ゲームがインストールされているフォルダ（例: `C:\Program Files (x86)\Steam\steamapps\common\Deadlock`）を開く
.. インストールされているフォルダが分からない場合は、steamを開いて、ライブラリからdeadlockを右クリックしてプロパティを開き、インストール済みファイルタブにある参照ボタンを押すと直接開けます。
. `game` フォルダを、先ほどダウンロードしたフォルダの中にある `game` フォルダで上書きします
.. 上書き後に以下のような構成になっていれば大丈夫です。（ファイルを追加したフォルダのみ表示しています）
+
[source, 例: C:\Program Files (x86)\Steam\steamapps\common\Deadlock\]
----
game
└─ citadel
   └─ resource
      └─ localization
         ├─ citadel_attributes
         │  ├─ citadel_attributes_english.txt など...
         │  └─ citadel_attributes_japanese.txt <- 今回追加したファイル
         ├─ citadel_gc
         │  ├─ citadel_gc_english.txt など...
         │  └─ citadel_gc_japanese.txt <- 今回追加したファイル                            
         ├─ citadel_heroes
         │  ├─ citadel_heroes_english.txt など...
         │  └─ citadel_heroes_japanese.txt <- 今回追加したファイル
         ├─ citadel_main
         │  ├─ citadel_main_english.txt など...
         │  └─ citadel_main_japanese.txt <- 今回追加したファイル
         └─ citadel_mods
            ├─ citadel_mods_english.txt など...
            └─ citadel_mods_japanese.txt <- 今回追加したファイル
----
. Steamを開いて、ライブラリからdeadlockを右クリックしてプロパティを開き、起動オプションに以下を入力してください。
+
[source, 起動オプション]
----
-language japanese
----
. Deadlockを起動して、日本語化されていればOKです

[[section-items-to-japanese]]
=== ショップのアイテム名を日本語にする場合
ショップのアイテム名を日本語にする場合は追加の作業が必要になります。 +
*<<section-settings,通常の日本語化設定>> を行った後* に `ショップのアイテム名を日本語にしたい人向け` フォルダの中にある `game` フォルダでさらに上書きします。 +
必ず *先に通常の日本語化設定を行う* 必要がありますので順番にはお気を付けください。

[[section-qanda]]
== Q&A
[qanda]
手順の通りにやりましたが日本語化出来ません::
よくあるミスとして以下が挙げられます。
* zipファイルを解凍していない
* 設定ファイルを別のフォルダに配置している
** gameフォルダの中にgameフォルダが入っていると日本語化されません
* 起動オプションの設定し忘れ
* 他サイトで対応した日本語化設定が残っている
** このサイトに書かれていること以外の設定をしていると正常に日本語化されない可能性があります
解凍したらファイル・フォルダが文字化けしています::
UTF-8対応の解凍ソフトを使って下さい。日本語なのでUTF-8でエンコードされています。 +
例: Windowsの標準機能, 7z

[[section-tips]]
== Tips
プレイに役立つサイトへのリンク集です。記載されていないおススメのサイトがあれば教えてください。

https://forums.playdeadlock.com/forums/changelog.10/::
Deadlock公式のパッチノートを確認できます。

https://deadlocktracker.gg/::
Match IDを入力することで、その試合の詳細な統計を確認できます。

https://deadlocktracker.gg/items::
アイテムの利用率/勝率を確認できます。ビルド作成時に役立ちます。メタ確認。

https://deadlocktracker.gg/heroes::
ヒーローの利用率/勝率を確認できます。メタ確認。

https://deadlockhero.com/builds::
ユーザー作成のビルド情報を確認できます。

https://tracklock.gg/players::
プレイヤーランキングを確認できます。

https://mobalytics.gg/deadlock/tier-list/heroes::
https://deadlockhero.com/tiers/hero-list::
ヒーローのティアリストを確認できます。

[[section-tou]]
== 利用規約

利用許諾::
本日本語化設定ファイル（以下「本ファイル」）は、全てのユーザーが動画や配信コンテンツを含むあらゆる目的で自由に使用できます。

免責事項::
当方は、本ファイルの利用により発生した一切の損害、損失、トラブルに対して、いかなる責任も負いません。

改変および再配布の禁止::
本ファイルの無断再編集および再配布を禁じます。当方が提供する最新バージョンの一貫性と品質を維持する目的と、誤解や不具合、トラブルの発生を防ぐためです。

== 更新履歴
2024/09/08::
* `Spirit` の翻訳を `スピリット` に統一しました。
* アイテム `Unstoppable` の説明をより自然な文章に修正しました。
* ショップのアイテム名（日本語）の表記ゆれを改善しました。 +
一部の不自然な日本語翻訳をカタカナ読みに変更しました。
* 本サイトに <<section-tou,利用規約>> セクションを追加しました。

2024/09/07::
* 最新版 `Build 5.123 2024/09/05 - 23:22:04` に対応しました。
* 本サイトに <<section-qanda,Q&A>> セクションを追加しました。

2024/09/06::
* 最新版 `Build 5.122 2024/09/05 - 15:28:41` に対応しました。
* 本サイトに <<section-tips,Tips>> セクションを追加しました。

2024/09/03::
* 最新版 `Build 5.120 2024/09/02 - 19:21:34` に対応しました。
* ヒーロー `Lady Geist` の1番目のアビリティが正しく表示されていない問題を修正しました。

2024/09/02::
* 最新版 `Build 5.118 2024/09/01 - 13:32:19` に対応しました。
* ショップのアイテム名を日本語にする方法を簡略化しました。
* ビデオ設定 `FSR2` のスケーリングモードの項目が全て表示出来ていなかった問題を修正しました。

2024/09/01::
*※ 大きな変更があります* +
https://x.com/steinsgg/status/1829208615779217490[Xで実施したアンケート]結果とフォームで頂いた提案に基づいて、以下の変更を加えました。

* *ショップのアイテム名を英語に戻しました。*
** アイテムは名前で並び順が変わってしまい、ビルドに影響が出てしまうためです。
* *ヒーローのアビリティ名をカタカナ読みに変更しました。*
** グローバルで同じ読み方が出来るように、且つどなたでも読めるカタカナ読みにします。
** 併せて英語のアビリティ名を説明欄に表示するようにしました + 
* `スロー`（移動速度低下）の表記を `スロウ` に修正しました。

2024/08/31::
* 最新版 `Build 5.115 2024/08/30 - 21:09:58` に対応しました。
* 一部アビリティ説明のパラメータが正しく引用されていない問題を修正しました。
* 起動オプションの誤記を修正しました。`en-dash (–)` で表記していましたが正しくは `hyphen (-)`
* ヒーロー `Viscous` の3番目のアビリティが正しく表示されていない問題を修正しました。
* ヒーロー `Warden` の3番目のアビリティをより分かりやすく再翻訳しました。
* `Health` の翻訳を `体力` に統一しました。

2024/08/30::
* 最新版 `Build 5.106 2024/08/29 - 23:02:44` に対応しました。
* ヒーロー `Mirage` のアビリティ `ファイアービートル` の説明文を修正しました。
* 公式で対応されたため `core` フォルダ配下の日本語化設定ファイルを削除しました。

2024/08/29::
* 最新版 `Build 5.095 2024/08/27 - 19:03:02` に対応しました。

2024/08/28::
* 日本語化設定ファイルを作成・公開
